[package]
name = "kraken-rs"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
nix = { version = "0.28.0", features = ["fs"] }
rayon = "1.5.3"
num_cpus = "1.16.0"
atty = "0.2.14"
getopts = "0.2.21"
memmap = "0.7.0"
byteorder = "1.5.0"
anyhow = "1.0.81"
libc = "0.2.153"
memmap2 = "0.9.4"
threadpool = "1.8.1"
flate2 = "1.0.28"
serde = { version = "1.0.197", features = ["derive"] }
bincode = "1.3.3"
serde_json = "1.0.115"

[features]
linear_probing = []
