[package]
name = "blah"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.16"
crossbeam = "0.8"
rayon = "1.10.0"
[features]
openmp = []
